version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODELS=deepseek-r1:1.5b
    restart: always
  
  frontend:
    # build: ./frontend
    image: southerncrossai/modelworks_frontend:frontend
    ports:
      - "3000:80"  
    restart: always

  backend:
    # build: ./backend
    image: southerncrossai/modelworks_frontend:backend
    ports:
      - "7860:7860"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: always

volumes:
  ollama-data: